theme: jekyll-theme-cayman

# Setup
title:        SIUE Statistical Laboratory Page
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Junvie Pailden
  url:        http://www.siue.edu/~jpailde/ 
  email:      jpailde at siue.edu
