theme: jekyll-theme-cayman

# Setup
title: SIUE Statistical Laboratory Page
baseurl: https://jpailden.github.io/rstatlab/

# About/contact
author: Junvie Pailden
author_email: jpailde at siue.edu
url: http://www.siue.edu/~jpailde/
