theme: jekyll-theme-modernist

# Setup
title:        SIUE Stat Classes Laboratory Page
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Junvie Pailden
  url:        http://www.siue.edu/~jpailde/ 
