theme: jekyll-theme-cayman

# Setup
title:        SIUE Stat Classes Laboratory Page
tagline:     This repository contains weekly statistical lab mateerials. using R.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Junvie Pailden
  url:        http://www.siue.edu/~jpailde/ 
