---
title: "Assignment 1"
output: html_notebook
---

```{r include=FALSE}
library(dplyr)
```

- Question 2 (Part A)

```{r}
oneParticle <- A1Q2 %>% filter(`Number of particles` >= 1)
fiveParticle <- A1Q2 %>% filter(`Number of particles` >= 5)
sum(fiveParticle$`Frequency`)
```

- Question 2 (Part B)

```{r}
fiveTenInc <- A1Q2 %>% filter(`Number of particles` >= 5 & `Number of particles` <= 10)
fiveTenExc <- A1Q2 %>% filter(`Number of particles` > 5 & `Number of particles` < 10)
sum(fiveTenInc$`Frequency`) / 100
sum(fiveTenExc$`Frequency`) / 100
```

- Question 4
```{r}
A1Q4 |> (\(x) x[x == 'A'])() |> length() 
```

- Question 6 (a)
```{r}
A1Q6$`blood pressure (in mmHg)` |>
  (\(x) round(x / 5) * 5)() |>
  sort() |>
  median()
```

- Question 6 (b)
```{r}
values <- c(128.6, 137.7, 148.4, 140.0, 123.7, 132.0, 118.3, 141.5, 143.2)
values |>
  (\(x) round(x / 5) * 5)() |>
  sort() |>
  median()
```

- Question 7 (a)
```{r}
vals <-
  c(
    0.721    ,
    0.857    ,
    0.867    ,
    0.904    ,
    0.922    ,
    0.936    ,
    0.981    ,
    1.010 ,
    1.039    ,
    1.050    ,
    1.081    ,
    1.121    ,
    1.133    ,
    1.162    ,
    1.233    ,
    1.039
  )
median(vals |> sort())
1.357 - 1.039
```

- Question 10
```{r}
range(A1Q10$`oxygen consumption (mL per kg per min)`)
49.6-24

```

- Question 11
```{r}
asphalt <- c(2796, 2924, 3049, 2826, 2893 )
meanAss<-mean(asphalt)
asphalt |> sort() |> median()

(2796+ 2924+ 3049+ 2826+ 2893)/5
var(asphalt)
```

- Question 12
```{r}
mean(A1Q12$`single-leg power`)
A1Q12$`single-leg power` |> sort() |> median()
```

- Question 13
```{r}
vals <- c(180.6 ,181.7 ,180.9 ,181.7 ,182.7 ,181.7,181.4 ,182.1 ,182.1 ,180.2 ,181.6 ,180.6)
range(vals)
180.2 - 182.7
sqrt(var(vals))
```

